export const DEFAULT_ACTION = 'DEFAULT_ACTION';
export const GET_POSTS = 'GET_POSTS';
export const FILTER_FOUND_POSTS = 'FILTER_FOUND_POSTS';
export const FILTER_LOST_POSTS = 'FILTER_LOST_POSTS';
export const UNFILTER_POSTS = 'UNFILTER_POSTS';
export const GET_CATEGORY = 'GET_CATEGORY';
